/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ApiEvidenceRouteImport } from './routes/api/evidence'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiUploadDocumentRouteImport } from './routes/api/upload-document'
import { Route as ApiAnalysisIdRouteImport } from './routes/api/analysis/$id'
import { Route as ApiDocumentsIdRouteImport } from './routes/api/documents.$id'
import { Route as ApiHistoryIdRouteImport } from './routes/api/history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceRoute = ApiEvidenceRouteImport.update({
  id: '/api/evidence',
  path: '/api/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadDocumentRoute = ApiUploadDocumentRouteImport.update({
  id: '/api/upload-document',
  path: '/api/upload-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalysisIdRoute = ApiAnalysisIdRouteImport.update({
  id: '/api/analysis/$id',
  path: '/api/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsIdRoute = ApiDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDocumentsRoute,
} as any)
const ApiHistoryIdRoute = ApiHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/history': typeof HistoryRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/evidence': typeof ApiEvidenceRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/api/upload-document': typeof ApiUploadDocumentRoute
  '/api/analysis/$id': typeof ApiAnalysisIdRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/history': typeof HistoryRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/evidence': typeof ApiEvidenceRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/api/upload-document': typeof ApiUploadDocumentRoute
  '/api/analysis/$id': typeof ApiAnalysisIdRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/history': typeof HistoryRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/evidence': typeof ApiEvidenceRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/api/upload-document': typeof ApiUploadDocumentRoute
  '/api/analysis/$id': typeof ApiAnalysisIdRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidence'
    | '/history'
    | '/knowledge-base'
    | '/reports'
    | '/settings'
    | '/api/analyze'
    | '/api/documents'
    | '/api/evidence'
    | '/api/history'
    | '/api/status'
    | '/api/upload-document'
    | '/api/analysis/$id'
    | '/api/documents/$id'
    | '/api/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidence'
    | '/history'
    | '/knowledge-base'
    | '/reports'
    | '/settings'
    | '/api/analyze'
    | '/api/documents'
    | '/api/evidence'
    | '/api/history'
    | '/api/status'
    | '/api/upload-document'
    | '/api/analysis/$id'
    | '/api/documents/$id'
    | '/api/history/$id'
  id:
    | '__root__'
    | '/'
    | '/evidence'
    | '/history'
    | '/knowledge-base'
    | '/reports'
    | '/settings'
    | '/api/analyze'
    | '/api/documents'
    | '/api/evidence'
    | '/api/history'
    | '/api/status'
    | '/api/upload-document'
    | '/api/analysis/$id'
    | '/api/documents/$id'
    | '/api/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceRoute: typeof EvidenceRoute
  HistoryRoute: typeof HistoryRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiDocumentsRoute: typeof ApiDocumentsRouteWithChildren
  ApiEvidenceRoute: typeof ApiEvidenceRoute
  ApiHistoryRoute: typeof ApiHistoryRouteWithChildren
  ApiStatusRoute: typeof ApiStatusRoute
  ApiUploadDocumentRoute: typeof ApiUploadDocumentRoute
  ApiAnalysisIdRoute: typeof ApiAnalysisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence': {
      id: '/api/evidence'
      path: '/api/evidence'
      fullPath: '/api/evidence'
      preLoaderRoute: typeof ApiEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-document': {
      id: '/api/upload-document'
      path: '/api/upload-document'
      fullPath: '/api/upload-document'
      preLoaderRoute: typeof ApiUploadDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analysis/$id': {
      id: '/api/analysis/$id'
      path: '/api/analysis/$id'
      fullPath: '/api/analysis/$id'
      preLoaderRoute: typeof ApiAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id': {
      id: '/api/documents/$id'
      path: '/$id'
      fullPath: '/api/documents/$id'
      preLoaderRoute: typeof ApiDocumentsIdRouteImport
      parentRoute: typeof ApiDocumentsRoute
    }
    '/api/history/$id': {
      id: '/api/history/$id'
      path: '/$id'
      fullPath: '/api/history/$id'
      preLoaderRoute: typeof ApiHistoryIdRouteImport
      parentRoute: typeof ApiHistoryRoute
    }
  }
}

interface ApiDocumentsRouteChildren {
  ApiDocumentsIdRoute: typeof ApiDocumentsIdRoute
}

const ApiDocumentsRouteChildren: ApiDocumentsRouteChildren = {
  ApiDocumentsIdRoute: ApiDocumentsIdRoute,
}

const ApiDocumentsRouteWithChildren = ApiDocumentsRoute._addFileChildren(
  ApiDocumentsRouteChildren,
)

interface ApiHistoryRouteChildren {
  ApiHistoryIdRoute: typeof ApiHistoryIdRoute
}

const ApiHistoryRouteChildren: ApiHistoryRouteChildren = {
  ApiHistoryIdRoute: ApiHistoryIdRoute,
}

const ApiHistoryRouteWithChildren = ApiHistoryRoute._addFileChildren(
  ApiHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceRoute: EvidenceRoute,
  HistoryRoute: HistoryRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiDocumentsRoute: ApiDocumentsRouteWithChildren,
  ApiEvidenceRoute: ApiEvidenceRoute,
  ApiHistoryRoute: ApiHistoryRouteWithChildren,
  ApiStatusRoute: ApiStatusRoute,
  ApiUploadDocumentRoute: ApiUploadDocumentRoute,
  ApiAnalysisIdRoute: ApiAnalysisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
